name: Generate Sitemap

on:
  schedule:
    # Runs at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Generate Sitemap
      run: |
        python assets/script/generate_sitemap.py

    - name: Debug Git Status
      run: |
        git status
        git log -1

    - name: Commit sitemap
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sitemap.xml
        git commit -m "Update sitemap"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
